# Site settings
title: selivan.github.io
#email: selivan.at.github@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just another IT blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://selivan.github.io" # the base hostname & protocol for your site
#twitter_username: i_got_no_twitter
github_username:  selivan

# Publish posts with a future date
future: true


# https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors
highlighter: rouge
markdown: kramdown
# Use Github Flavored Markdown
kramdown:
   input: GFM
timezone: Europe/Moscow
gems:
  # RSS feeds
  - jekyll-feed
  # https://help.github.com/articles/redirects-on-github-pages/ Example:
  #---
  #redirect_from: "/foo"
  #---
  - jekyll-redirect-from
  # GitHub Emoji https://help.github.com/articles/emoji-on-github-pages/
  # Example: :+1:
  - jemoji
  # GitHub @mentions https://help.github.com/articles/mentions-on-github-pages/
  # Example: @username
  - jekyll-mentions
  # Jekyll-seo-tag: add metadata tags for search engines and social networks to better index and display site's content
  # https://github.com/jekyll/jekyll-seo-tag#usage
  - jekyll-seo-tag
  # GitHub Sitemap - generate /sitemap.xml for search engines
  # https://help.github.com/articles/sitemaps-for-github-pages/
  # Should be listed last to include content generated by other plugins
  - jekyll-sitemap

# Exclude files and directories from jekyll conversion
exclude: [TODO.md]
